python3 rose2arc.py arc/ball/bytecodes.bin -c arc/ball/constants.bin -s arc/ball/colorscript.bin -o arc/ball.asm
python3 rose2arc.py arc/circle/bytecodes.bin -c arc/circle/constants.bin -s arc/circle/colorscript.bin -o arc/circle.asm
python3 rose2arc.py arc/everyway/bytecodes.bin -c arc/everyway/constants.bin -s arc/everyway/colorscript.bin -o arc/everyway.asm
python3 rose2arc.py arc/chiperia/bytecodes.bin -c arc/chiperia/constants.bin -s arc/chiperia/colorscript.bin -o arc/chiperia.asm
python3 rose2arc.py arc/tree/bytecodes.bin -c arc/tree/constants.bin -s arc/tree/colorscript.bin -o arc/tree.asm
python3 rose2arc.py arc/teaser/bytecodes.bin -c arc/teaser/constants.bin -s arc/teaser/colorscript.bin -o arc/teaser.asm
python3 rose2arc.py arc/jesuis/bytecodes.bin -c arc/jesuis/constants.bin -s arc/jesuis/colorscript.bin -o arc/jesuis.asm
python3 rose2arc.py arc/euphoria/bytecodes.bin -c arc/euphoria/constants.bin -s arc/euphoria/colorscript.bin -o arc/euphoria.asm
python3 rose2arc.py arc/frustration/bytecodes.bin -c arc/frustration/constants.bin -s arc/frustration/colorscript.bin -o arc/frustration.asm
python3 rose2arc.py arc/waytoorude/bytecodes.bin -c arc/waytoorude/constants.bin -s arc/waytoorude/colorscript.bin -o arc/waytoorude.asm
python3 rose2arc.py arc/revision/bytecodes.bin -c arc/revision/constants.bin -s arc/revision/colorscript.bin -o arc/revision.asm
